services:
  db:
    image: postgres:16.9
    container_name: taylor-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - taylor-net
    volumes:
      - pgdata:/var/lib/postgresql/data
    command:
      ["postgres", "-c", "max_connections=300", "-c", "shared_buffers=512MB"]
  redis:
    image: redis:7-alpine
    container_name: taylor-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks: [taylor-net]
  backend:
    build: ./backend
    container_name: taylor-backend
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - taylor-net
  worker:
    build: ./backend
    container_name: taylor-worker
    depends_on:
      - redis
      - db
    restart: unless-stopped
    env_file: [.env]
    networks: [taylor-net]
    entrypoint: ["bash", "-lc", "pdm run python worker.py"]

  frontend:
    build: ./frontend
    container_name: taylor-frontend
    depends_on:
      - backend
    ports:
      - "3030:3030"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - taylor-net

  nginx:
    build: ./nginx
    container_name: taylor-nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - taylor-net
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/conf:/etc/letsencrypt
  certbot:
    image: certbot/certbot
    container_name: taylor-certbot
    networks:
      - taylor-net
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'while :; do sleep 12h & wait $${!}; certbot renew; done;'"

networks:
  taylor-net:
volumes:
  pgdata:
